# Generated by Django 3.0.6 on 2021-08-12 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquetes',
            name='paquetePerfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Soluciones.perfil'),
        ),
    ]
