# Generated by Django 3.0.6 on 2021-08-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopaq',
            name='fechaPago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
