# Generated by Django 3.0.6 on 2021-08-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrpago',
            name='foto',
            field=models.ImageField(null=True, upload_to='foto'),
        ),
    ]
