# Generated by Django 3.0.6 on 2021-06-03 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tematicas',
            fields=[
                ('temaID', models.AutoField(primary_key=True, serialize=False)),
                ('temaNombre', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='soluciones',
            name='problemaTema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Soluciones.tematicas'),
        ),
    ]
