# Generated by Django 3.0.6 on 2021-08-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0002_usuariopaq_fechapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopaq',
            name='vencido',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
