# Generated by Django 3.0.6 on 2021-06-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0002_auto_20210603_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soluciones',
            name='problemaSolucion',
            field=models.FileField(null=True, upload_to='soluciones'),
        ),
    ]
