# Generated by Django 3.0.6 on 2021-10-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0002_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solucionadores',
            name='solucionadorPais',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
