# Generated by Django 3.0.6 on 2021-06-18 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Soluciones', '0003_auto_20210608_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='paquetes',
            fields=[
                ('paqueteID', models.AutoField(primary_key=True, serialize=False)),
                ('paqueteCod', models.CharField(max_length=50, null=True)),
                ('paqueteDesc', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIni', models.DateField(blank=True, null=True)),
                ('fechaFin', models.DateField(blank=True, null=True)),
                ('paqueteMio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Soluciones.paquetes')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
