# Generated by Django 3.0.6 on 2021-08-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0003_usuariopaq_vencido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopaq',
            name='vencido',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
