# Generated by Django 3.0.6 on 2021-06-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0004_paquetes_usuariopaq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopaq',
            name='fechaFin',
        ),
        migrations.AddField(
            model_name='paquetes',
            name='cantidadDia',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paquetes',
            name='precio',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuariopaq',
            name='activo',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
