# Generated by Django 3.0.6 on 2021-06-18 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0005_auto_20210618_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopaq',
            name='libro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Soluciones.libros'),
        ),
        migrations.AddField(
            model_name='usuariopaq',
            name='tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Soluciones.tematicas'),
        ),
    ]
