# Generated by Django 3.0.6 on 2021-06-18 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0006_auto_20210618_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='tematicas',
            name='idLibro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Soluciones.libros'),
        ),
        migrations.AlterField(
            model_name='paquetes',
            name='cantidadDia',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paquetes',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
