# Generated by Django 3.0.6 on 2021-06-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0007_auto_20210618_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopaq',
            name='libro',
        ),
    ]
