# Generated by Django 3.0.6 on 2021-06-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0008_remove_usuariopaq_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopaq',
            name='usuario',
            field=models.IntegerField(null=True),
        ),
    ]
