# Generated by Django 3.0.6 on 2021-06-27 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0009_auto_20210618_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paquetes',
            old_name='cantidadDia',
            new_name='paqueteDias',
        ),
        migrations.RenameField(
            model_name='paquetes',
            old_name='precio',
            new_name='paquetePrecio',
        ),
        migrations.RemoveField(
            model_name='usuariopaq',
            name='tema',
        ),
        migrations.AddField(
            model_name='paquetes',
            name='paqueteTema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Soluciones.tematicas'),
        ),
        migrations.AddField(
            model_name='soluciones',
            name='problemaPkt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Soluciones.paquetes'),
        ),
    ]
