# Generated by Django 3.0.6 on 2021-06-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0010_auto_20210627_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquetes',
            name='paqueteDesc',
        ),
        migrations.AddField(
            model_name='paquetes',
            name='paqueteCant',
            field=models.IntegerField(null=True),
        ),
    ]
