# Generated by Django 3.0.6 on 2021-07-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0011_auto_20210627_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquetes',
            name='paqueteDescr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
